/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ExtendedSolidity } from "./ExtendedSolidity";
export type { StakingContract } from "./StakingContract";
