/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface StakingContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_PEOPLE"
      | "add"
      | "addUser"
      | "getAge"
      | "getUserCount"
      | "owner"
      | "userAddresses"
      | "userDetails"
      | "users"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Log"
      | "NumberUpdated"
      | "UserAdded"
      | "UserWithdrew"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_PEOPLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "add",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addUser",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userDetails",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "MAX_PEOPLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace LogEvent {
  export type InputTuple = [func: string, gas: BigNumberish];
  export type OutputTuple = [func: string, gas: bigint];
  export interface OutputObject {
    func: string;
    gas: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NumberUpdatedEvent {
  export type InputTuple = [oldNumber: BigNumberish, newNumber: BigNumberish];
  export type OutputTuple = [oldNumber: bigint, newNumber: bigint];
  export interface OutputObject {
    oldNumber: bigint;
    newNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserAddedEvent {
  export type InputTuple = [
    account: AddressLike,
    name: string,
    age: BigNumberish,
    balance: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    name: string,
    age: bigint,
    balance: bigint
  ];
  export interface OutputObject {
    account: string;
    name: string;
    age: bigint;
    balance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserWithdrewEvent {
  export type InputTuple = [
    account: AddressLike,
    name: string,
    age: BigNumberish,
    balance: BigNumberish
  ];
  export type OutputTuple = [
    account: string,
    name: string,
    age: bigint,
    balance: bigint
  ];
  export interface OutputObject {
    account: string;
    name: string;
    age: bigint;
    balance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingContract extends BaseContract {
  connect(runner?: ContractRunner | null): StakingContract;
  waitForDeployment(): Promise<this>;

  interface: StakingContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_PEOPLE: TypedContractMethod<[], [bigint], "view">;

  add: TypedContractMethod<
    [a: BigNumberish, b: BigNumberish],
    [bigint],
    "view"
  >;

  addUser: TypedContractMethod<
    [_name: string, _age: BigNumberish, _ethnicity: BigNumberish],
    [void],
    "payable"
  >;

  getAge: TypedContractMethod<[_years: BigNumberish], [bigint], "view">;

  getUserCount: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  userAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  userDetails: TypedContractMethod<
    [_address: AddressLike],
    [[string, bigint] & { name: string; age: bigint }],
    "view"
  >;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        name: string;
        age: bigint;
        ethnicity: bigint;
        balance: bigint;
        index: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_PEOPLE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<[a: BigNumberish, b: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "addUser"
  ): TypedContractMethod<
    [_name: string, _age: BigNumberish, _ethnicity: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getAge"
  ): TypedContractMethod<[_years: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "userDetails"
  ): TypedContractMethod<
    [_address: AddressLike],
    [[string, bigint] & { name: string; age: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint, boolean] & {
        name: string;
        age: bigint;
        ethnicity: bigint;
        balance: bigint;
        index: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Log"
  ): TypedContractEvent<
    LogEvent.InputTuple,
    LogEvent.OutputTuple,
    LogEvent.OutputObject
  >;
  getEvent(
    key: "NumberUpdated"
  ): TypedContractEvent<
    NumberUpdatedEvent.InputTuple,
    NumberUpdatedEvent.OutputTuple,
    NumberUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UserAdded"
  ): TypedContractEvent<
    UserAddedEvent.InputTuple,
    UserAddedEvent.OutputTuple,
    UserAddedEvent.OutputObject
  >;
  getEvent(
    key: "UserWithdrew"
  ): TypedContractEvent<
    UserWithdrewEvent.InputTuple,
    UserWithdrewEvent.OutputTuple,
    UserWithdrewEvent.OutputObject
  >;

  filters: {
    "Log(string,uint256)": TypedContractEvent<
      LogEvent.InputTuple,
      LogEvent.OutputTuple,
      LogEvent.OutputObject
    >;
    Log: TypedContractEvent<
      LogEvent.InputTuple,
      LogEvent.OutputTuple,
      LogEvent.OutputObject
    >;

    "NumberUpdated(uint256,uint256)": TypedContractEvent<
      NumberUpdatedEvent.InputTuple,
      NumberUpdatedEvent.OutputTuple,
      NumberUpdatedEvent.OutputObject
    >;
    NumberUpdated: TypedContractEvent<
      NumberUpdatedEvent.InputTuple,
      NumberUpdatedEvent.OutputTuple,
      NumberUpdatedEvent.OutputObject
    >;

    "UserAdded(address,string,uint8,uint256)": TypedContractEvent<
      UserAddedEvent.InputTuple,
      UserAddedEvent.OutputTuple,
      UserAddedEvent.OutputObject
    >;
    UserAdded: TypedContractEvent<
      UserAddedEvent.InputTuple,
      UserAddedEvent.OutputTuple,
      UserAddedEvent.OutputObject
    >;

    "UserWithdrew(address,string,uint8,uint256)": TypedContractEvent<
      UserWithdrewEvent.InputTuple,
      UserWithdrewEvent.OutputTuple,
      UserWithdrewEvent.OutputObject
    >;
    UserWithdrew: TypedContractEvent<
      UserWithdrewEvent.InputTuple,
      UserWithdrewEvent.OutputTuple,
      UserWithdrewEvent.OutputObject
    >;
  };
}
