/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attackerContractSol from "./AttackerContract.sol";
export type { attackerContractSol };
import type * as stakingContractSol from "./StakingContract.sol";
export type { stakingContractSol };
export type { YourContract } from "./YourContract";
