/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ExtendedSolidity__factory } from "./ExtendedSolidity__factory";
export { StakingContract__factory } from "./StakingContract__factory";
